default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.6
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [--fix, --select=I, --verbose]
      - id: ruff
        types_or: [ python, pyi, jupyter]
        args: [--verbose]
      # Run the formatter.
      - id: ruff-format
        args: [--verbose]
        types_or: [ python, pyi, jupyter ]
