# TODO: switch to chartboost/ruff-action when it's ready
# for now it doesn't work with ruff>=0.5.0
# 
# also there is a problem with solution below
# it runs on all files and not only changed ones
# we can fix it, but it's to much time
# it's easier to use action once it's ready
name: Ruff
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.18"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.5.6
      # - name: ruff check
      #   run: ruff check --verbose --output-format=github .
      - name: ruff format check
        run: ruff format --check --verbose .
